server.port=8080

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# PostgreSQL RDS
spring.datasource.url=jdbc:postgresql://database-uady.ckudetdcrnsb.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Chepo2004
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# AWS Credentials
aws.region=us-east-1
aws.access-key-id=ASIAY5MUHN7B55KV4H6A
aws.secret-access-key=jBwS2G62WQcyJNuFMHnOC5Zuuf/3RPws1TxvO+H0
aws.session-token=IQoJb3JpZ2luX2VjEKH//////////wEaCXVzLXdlc3QtMiJHMEUCIFRJAl6jsr8Y/JgX6cDZihzAUqUGY7vKHURtPH2WSiDgAiEAwVxiplcyIffelVGIjlSwtJ7P/qDvOx84Y/7du0m/+h0qsAIIahAAGgw2MTI4ODA1NzY0NTEiDC+G3W+ABSN8HzUhUiqNAnBWaEsxo2vB94ILtrSoyg5nfG8kevIuDK59v73jQvMG/upa6X9O3ACer77xSrAidQn1/sOrMnl9NjURzDfasj75YKpJYVcvrJ9VW1UGHo13R1YaxZFJHXihcIox7pcOkOFHgg9y7NIZWcnlqZEEJdWJsWiLXylh6qAiatJyUz+2fLm7nWAo+vS22RSjjQbLcZsUF5JMREgp/vHATkmM4NT7nQk5uljxihNiUdZpKCkFfFC9qaaB+TOSr31z9Gqz/9BzaEIZYdQIpN7Zzwxj699OBJeNpPs434tw6dLIyEBGHS88j9o9xNX543N2xuCgGHEhPt1zgiOPl/qD1CQoEOG7E+hjbN3BIQeJp5+xMOXemdAGOp0BABr6jvI3gLvAdHXX+uYEKvZsfzkdR/g7cW150cvZMhXN1aFQzFXP6u/QKWvH6R3A4fSZMQ8EKxXcDey0/94yGnfa1ucdooFg9QvOcLiT9YvvlpGgLi3ReV4JOMBEULzYpS3uUyG/kaJFhXGzNRMy8ZBbxeQh5A3fcJiv7QCcFZ0cTl4VDcSZm7ijbR+0QysCRgAJpJHc/2ViGN8bMQ
# AWS SNS
aws.sns.topic-arn=arn:aws:sns:us-east-1:612880576451:Avisos-UADY

# AWS S3
aws.s3.bucket=uady-alumnos-612880576451-us-east-1-an
