server.port=8080

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# PostgreSQL RDS
spring.datasource.url=jdbc:postgresql://database-uady.ckudetdcrnsb.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Chepo2004
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# AWS Credentials
aws.region=us-east-1
aws.access-key-id=ASIAY5MUHN7BSTUWKDQM
aws.secret-access-key=0xNsWOuFqbmuxW7J5NeTlgkbK+2sU/kJwRCBxFdS
aws.session-token=IQoJb3JpZ2luX2VjEIr//////////wEaCXVzLXdlc3QtMiJHMEUCIQDVXpghvGZnP7R1FL0OIEYM1//wXzBjuf4jFW9M+nz8DgIgEPpjXhY7lI/9eQgU7xtHjCZHpaK8DhMFREJ6sDJQRCoqsAIIUxAAGgw2MTI4ODA1NzY0NTEiDCTVDc6s38Fc1Dm9FSqNAgr7PSh/qn5fxPgAgc+sW3mnVFKO2rtbb3dKUKbxbicqirwXGWaPcCv7mRLNgUuo0hgFA4NDoAYbSLvGI00Pn3OsGnKg6+nbcCuk+16T0ShnGaUhnb0v88aX1xSP3sDOomVvD8taty3Fsi2mPgMcUNhBRm4XYcU2R3r1gMIVTMUJTShcVa7V3oJ0S4kwxChPevD1BrbO20GqbN31zmCztOv6zl8nRUdxSYO8zCJCCyueHDGulNUKRybzSUMG1la/SztQx9yLPc/krvDwPDNCRe8R8Lx3RnLRGzku1ZqAlMi5dTjcHf+7McG2anOdJRgCW8nLXyM+sCcxmYqLf0Ni9vzqveWo3tUQI3hxeLv8MKTglNAGOp0B9i+vqL7raZoGxmwaLIuvjgs9lOGDdS4lPzdMVPKL77nxZxBoezplEfkXSIMZFMeMNFa1rjtiT5T2BGgWHC+XtJvCbXagI2jBq4fo6Zbs4Un5PLenO1OsHV7MpHSufvdtNMThaDuay8fzsMhMHXWivRzQrtLUfNcXLktLlRGF4mOsVv0N+0RgSIEWZGa/nHPgdBsI7z7tctmisR1NPw
# AWS SNS
aws.sns.topic-arn=arn:aws:sns:us-east-1:612880576451:Avisos-UADY

# AWS S3
aws.s3.bucket=uady-alumnos-612880576451-us-east-1-an
