server.port=8080

spring.mvc.throw-exception-if-no-handler-found=true
spring.web.resources.add-mappings=false

# PostgreSQL RDS
spring.datasource.url=jdbc:postgresql://database-uady.ckudetdcrnsb.us-east-1.rds.amazonaws.com:5432/postgres
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=Chepo2004
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# AWS Credentials
aws.region=us-east-1
aws.access-key-id=ASIAY5MUHN7B5ETBJOOE
aws.secret-access-key=InOiDLQI7WgkRCdd2HmnQi7LdMcaH3ELwheeR6fs
aws.session-token=IQoJb3JpZ2luX2VjEG8aCXVzLXdlc3QtMiJHMEUCIQD2SogNm/xWoE2ZS89cwKVioXv955rD971Q2Hhgb0iAbwIgbbzw8uXILBi9cNoq6I3tp178nUIFBx33nvL2Onj5/NoqsAIINxAAGgw2MTI4ODA1NzY0NTEiDADK/0BMoX7hROTsnSqNAoykW8s7GDYKBTxTj2JHkyMbjn/tkCVpxib9I95heQK//jG/kF5Fboj5EnD29E4HNfeBCI+dUvlmuejXD7BZwuB5iqnCFqUoGhp7sS2rzOyl10xlZOTSlAmqoQ0YbhKx1JLFaB634ItBvGknxcX99esew4MMHXzxmn0llG4BX1/zDnDCTZiG2UTsDlRW4zCu93IHrICkx1ufnaPUZI1vklzTO5XdYjauJL5rVEtmWBd6D1P/192EDSGPNLqHsHozj8d5od+ScBVeextbR9vXggspMRW3ogYyNi5KTlaha0atrwsAKlWTTsYTqwZ0OQ78S8yaa6d7CSHuXtSlACTQ+OQ6LSLMNXZ5W/WiaBY9MJnOjtAGOp0Bt6vRLq+1VhoAT2kWrqMcWQun252/CZ1w4bxg3mpegledQzQTZVIwzL0pDx9Be67wSGWb/+DI6QxIXJUMyXd4vhTAtb4eJ76yyKjytnkIszLmcnukpa/OHR8ir+I/mY3FyGjDHokJ4QA0kTOBoTKdspYeSWhS8Q4HBWi7vE740raTlykU3klKk6QRBt1sOGcs4qg1uqT2zz8YE0exfw
# AWS SNS
aws.sns.topic-arn=arn:aws:sns:us-east-1:612880576451:Avisos-UADY

# AWS S3
aws.s3.bucket=uady-alumnos-612880576451-us-east-1-an
